name = "my_example_pkg"
uuid = "9eede454-80f6-4f1b-bc85-709da3b78da6"
authors = ["sirojan09 <sirojan09@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
